export const Endpoints = {
    login: "auth/login",
    register: "auth/register",
    artists: "api/artists",
    me: "api/users/me",
    songs: "api/songs",
    mostWantedSongs: "api/songs/most-wanted",
    listOfAlbums: "api/albums",
    artistOperation: "api/artists",
    albumOperation: "api/albums",
    playlistOperation: "api/playlists",
    playlistOperationPublic: "api/playlists/public",
    songsForAlbum: "api/songs/no-album",
    listOfSongs: "api/songs",
    getAlbumById: "api/albums/search",
    updateSong: "api/songs",
    getSongsForAlbumId: "api/albums/songs",
    updateAlbumTitle: "api/albums/title",
    updateAlbumDetails: "api/albums/detail",
    getPersonsForBand: "api/artists/persons",
    changePassword: "api/users/change-password",
    searchSongs: "api/songs/search",
    searchAlbums: "api/albums/search",
    searchArtist: "api/artists/search",
    getUserPlaylists: (userId: number, isPublic: boolean) =>
    `api/users/${userId}/playlists?public=${isPublic}`,
    updateArtist: "api/artists",
    userDetails:"api/users",
    userOperations: "api/admins/users",
    updateUser: "api/users/update",
    followedPlaylists: "api/playlists/me/followed",
    ownedPlaylists: "api/playlists/me/owned",
    deletePlaylist:"api/playlists/delete",
    paginateSongs: "api/songs/paginate",
    paginateAlbums: "api/albums/paginate",
    paginateArtists: "api/artists/paginate",
    paginatePublicPlaylists: "api/playlists/public/paginate",
  getFollowed:    (userId: number) => `api/users/${userId}/playlists/followed`,
  followPlaylist: (userId: number, playlistId: number) => `api/users/${userId}/playlists/follow/${playlistId}`,
  unfollowPlaylist:(userId: number, playlistId: number) => `api/users/${userId}/playlists/unfollow/${playlistId}`,
    getPlaylistById:"api/playlists/find"
}
